V01-28: put console.log function to the file
meVeri/Git-basics pull request #15
Opened 2023-09-01 17:31 UTC by meVeri

2023-09-01 19:12 UTC, theXaMi requested changes
I see that you changed the formatting of the entire file. Why is that? 😛

2023-09-01 19:12 UTC, theXaMi commented on OldWeb/oldweb.html
> +console.log(a)
This needs to be done in JavaScript, not HTML. Here it is just a text. You can put JavaScript here using `<script>` tag, or you can do it in the `index.tsx` file.

2023-09-01 19:40 UTC, meVeri commented on OldWeb/oldweb.html
> +console.log(a)
both lines, or just one?

2023-09-01 19:50 UTC, meVeri commented
> I see that you changed the formatting of the entire file. Why is that? 😛

Just for test, no reason for that, but i can change it if u want xd

2023-09-01 21:25 UTC, meVeri commented
Ready to Rewiev

2023-09-15 23:55 UTC, theXaMi commented
`console.log()`s are looking good, but commits are terrible. The `D3D` and `asdasdasd` files are not a part of the task, please remove them and squash the commits.

2023-09-15 23:56 UTC, theXaMi requested changes
Please fix this commit mess

2023-09-23 17:29 UTC, theXaMi commented on OldWeb/oldweb.html
> +console.log(a)
Both of them 😛

2023-09-23 17:53 UTC, theXaMi approved these changes
:+1:

2023-09-24 19:04 UTC, theXaMi approved these changes

2023-10-12 15:55 UTC, merged